'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VR_GO_DespachoNotaVentaXCliente
    Public Property oanumi As Integer
    Public Property oafdoc As Nullable(Of Date)
    Public Property ccdesc As String
    Public Property cbdesc As String
    Public Property canumi As Integer
    Public Property cadesc As String
    Public Property oaobs As String
    Public Property obpcant As Nullable(Of Decimal)
    Public Property obpbase As Nullable(Of Decimal)
    Public Property obptot As Nullable(Of Decimal)
    Public Property oaest As Nullable(Of Integer)
    Public Property oaccbnumi As Integer
    Public Property Total As Nullable(Of Decimal)

End Class
